import { CssBaseline, ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import BreakpointsProvider from 'providers/BreakpointsProvider';
import SettingsProvider from 'providers/SettingsProvider';
import { theme } from 'theme/theme';
// import { _api } from '@iconify/react';
// import fetch from 'cross-fetch';
// //  import fetch from 'node-fetch';

// // Set Fetch API before doing anything
// _api.setFetch(fetch);

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('dasj');

  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <BreakpointsProvider>
            <SettingsProvider>
              <CssBaseline />
              {children}
            </SettingsProvider>
          </BreakpointsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
