import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { CssBaseline, ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import BreakpointsProvider from 'providers/BreakpointsProvider';
import SettingsProvider from 'providers/SettingsProvider';
import { theme } from 'theme/theme';
import { plusJakartaSans } from 'theme/typography';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={plusJakartaSans.className}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <BreakpointsProvider>
              <SettingsProvider>
                <CssBaseline />
                {children}
              </SettingsProvider>
            </BreakpointsProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
